/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: eaa20e8331859a18fd8e9a8d22e1ff2b)
interface __BaseEnv_Env {
  SOURCE_ORIGIN: "https://filerouter.dev"
  PDF_INSPECTOR_CONTAINERS: DurableObjectNamespace<
    import("./src/index").PdfInspectorContainer
  >
  LITEPARSE_CONTAINERS: DurableObjectNamespace<
    import("./src/index").LiteParseContainer
  >
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index")
    durableNamespaces: "PdfInspectorContainer" | "LiteParseContainer"
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string
}
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, "SOURCE_ORIGIN">
  > {}
}
